[package]
name = "pine_trans"
version = "0.1.0"
authors = ["swgillespie <sean.william.g@gmail.com>"]

[dependencies.pine_typecheck]
path = "../pine_typecheck"

[dependencies]
log = "0.3.1"
llvm_sys = "0.1.3"